# NIFTY 200 Index — NSE Tickers (Royal Gold Edition)

NIFTY200 = [
    # NIFTY 50
    "ADANIENT.NS","ADANIPORTS.NS","APOLLOHOSP.NS","ASIANPAINT.NS","AXISBANK.NS",
    "BAJAJ-AUTO.NS","BAJFINANCE.NS","BAJAJFINSV.NS","BPCL.NS","BHARTIARTL.NS",
    "BRITANNIA.NS","CIPLA.NS","COALINDIA.NS","DIVISLAB.NS","DRREDDY.NS",
    "EICHERMOT.NS","GRASIM.NS","HCLTECH.NS","HDFCBANK.NS","HDFCLIFE.NS",
    "HEROMOTOCO.NS","HINDALCO.NS","HINDUNILVR.NS","ICICIBANK.NS","ITC.NS",
    "INDUSINDBK.NS","INFY.NS","JSWSTEEL.NS","KOTAKBANK.NS","LT.NS",
    "M&M.NS","MARUTI.NS","NESTLEIND.NS","NTPC.NS","ONGC.NS",
    "POWERGRID.NS","RELIANCE.NS","SBILIFE.NS","SBIN.NS","SHREECEM.NS",
    "SUNPHARMA.NS","TATACONSUM.NS","TATAMOTORS.NS","TATASTEEL.NS","TCS.NS",
    "TECHM.NS","TITAN.NS","ULTRACEMCO.NS","WIPRO.NS",

    # NIFTY NEXT 50
    "ABB.NS","ACC.NS","ADANIGREEN.NS","ADANITRANS.NS","AMBUJACEM.NS","AUROPHARMA.NS",
    "BANKBARODA.NS","BERGEPAINT.NS","BIOCON.NS","BOSCHLTD.NS","CANBK.NS","CHOLAFIN.NS",
    "DABUR.NS","DLF.NS","GAIL.NS","GLAND.NS","GODREJCP.NS","HAVELLS.NS","ICICIPRULI.NS",
    "IGL.NS","INDIGO.NS","INDUSTOWER.NS","JINDALSTEL.NS","L&TFH.NS","LICI.NS",
    "LUPIN.NS","MARICO.NS","MCDOWELL-N.NS","MFSL.NS","MUTHOOTFIN.NS","NAUKRI.NS",
    "PEL.NS","PIDILITIND.NS","PIIND.NS","PNB.NS","RECLTD.NS","SAIL.NS","SIEMENS.NS",
    "SRF.NS","TORNTPHARM.NS","UBL.NS","VEDL.NS","VOLTAS.NS","ZOMATO.NS",

    # NIFTY MIDCAP 50
    "AARTIIND.NS","ALKEM.NS","APLLTD.NS","ASTRAL.NS","ATUL.NS","BALKRISIND.NS",
    "BHARATFORG.NS","CUMMINSIND.NS","DEEPAKNTR.NS","ESCORTS.NS","GMRINFRA.NS",
    "GRANULES.NS","GUJGASLTD.NS","HAL.NS","HINDPETRO.NS","IDFCFIRSTB.NS",
    "INDIAMART.NS","IPCALAB.NS","JUBLFOOD.NS","LALPATHLAB.NS","MPHASIS.NS",
    "PAGEIND.NS","PERSISTENT.NS","POLYCAB.NS","RAJESHEXPO.NS","TATACHEM.NS",
    "TRENT.NS","TVSMOTOR.NS","WHIRLPOOL.NS","ZEEL.NS"
]
